//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterpeace2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Cart_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string User_Id { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
